### ISSUE TITLE
At-Least-Once processing and acknowledgements

### ISSUE THREAD

**Issue by clarkbreyman** [hdinsight/eventhubs-client#1]
It appears from EventHubReceiver.java#L83 that, even though the receiver is operating in AcknowledgeMode.ALO, that messages are acknowledged immediately on receipt. 

This makes it impossible to ensure that messages are completely processed by consumer logic before acknowledgement. If the consumer receives a messages an aborts prior to completely processing the message, the whole payload is considered processed and the data is lost.

**Comment by rtandonmsft** [comment]
Thanks @clarkbreyman for reporting this. Will get this looked at.

**Comment by jonmer85** [comment]
Hey @rtandonmsft Is this still an ongoing issue?

**Comment by jonmer85** [comment]
@rtandonmsft This is Jon Meran from Schneider BTW :)

**Comment by clarkbreyman** [comment]
@jonmer85 - Here's the link to the specific line. The messages are acked when they are received, not when the events they contain are processed. If you crash after receiving but before processing, the events are lost. 

https://github.com/hdinsight/eventhubs-client/blob/master/src/main/java/com/microsoft/eventhubs/client/EventHubReceiver.java#L83

**Comment by jonmer85** [comment]
Thanks @clarkbreyman for my specific case this may not be a huge problem since I will likely use this library for sending messages, not receiving them. We rely on Storm to process messages out of the Hub so we need the Storm component to ack the messages.

**Comment by rtandonmsft** [comment]
@jonmer85 You deduction is right, for Storm case (for which the spout/receiver) were originally written, once the message enters Storm, it's Storm guarantee to ensure the message is fully processed. So acknowledging the message on server side will not make a difference as all the check-pointing information is stored in Zookeeper.

@clarkbreyman What scenario are you using this client for? The same problem does not exist if you use https://github.com/hdinsight/storm-eventhubs that uses this underneath. I had reached out to event-hubs team about this issue and did not get a response. What behavior change do you expect? Do you want a separate acknowledge method to be exposed in receiver? Have you looked at Storm to solve your message processing guarantees?

**Comment by jonmer85** [comment]
Thanks for your quick responses as always @rtandonmsft !

**Comment by clarkbreyman** [comment]
@rtandonmsft - We're looking at a variety of applications which cannot tolerate any message loss (requires at-least-once *processing*), so if our consumer crashes or disappears before the consumer processing is complete, the message must not be acknowledged.

**Comment by clarkbreyman** [comment]
For these applications, we would be considering Event Hubs as an alternative to Kafka, not as a spooling mechanism for Storm.

**Comment by rtandonmsft** [comment]
Closing this issue, as this client was mostly written to support Storm. Newer java applications should consider switching to: https://github.com/Azure/azure-event-hubs
