### ISSUE TITLE
EventHubsSender keeps failing to send messages once it hits ConnectionClosedException

### ISSUE THREAD

**Issue by sjkwak** [hdinsight/eventhubs-client#12]
EventHubsSender keeps failing to send messages once it hits ConnectionClosedException and it is not recoverable until EventHubsSender object is recreated.

<< Error message >>
ERROR c.m.eventhubs.client.EventHubSender - org.apache.qpid.amqp_1_0.client.ConnectionClosedException: The connection was inactive for more than the allowed period of time.

**Comment by rtandonmsft** [comment]
The PR is now merged. Thanks for the fix!
