### ISSUE TITLE
Unable to retrieve message from all partitions in parallel.

### ISSUE THREAD

**Issue by cjpraful** [hdinsight/eventhubs-client#4]
i had set up event bus with 8 partition. I tried sending and receive message from event hub bby running 2 jobs one for sender and reciever. Send was successfully done . In Sender program, if we set partitionid as -1 it was getting delivered in round robin manner . But for Receiver program I was receiving messages from only any one of the partition, i.e if we set partition id as 4 , was able to retrieve message of that corresponding partition only.
Could you please check, suggest workaround and also do correct me if it was mistake in my understanding.

**Comment by shanyu** [comment]
EventHubReceiver is tied to a specific partition. If you want to receive messages from all partitions, you can create an array of receivers and do receive in a round robin fashion. Usually people use parallel receive in a distributed system, like Storm or Spark Streaming, in which case, each receiver instance on a separate node is responsible for receiving from 1 partition.

**Comment by rtandonmsft** [comment]
@cjpraful Have you looked at https://github.com/hdinsight/storm-eventhubs which demonstrates what @shanyu mentioned above?

**Comment by cjpraful** [comment]
thanks for the input @shanyu & @rtandonmsft . I tried with spark  and it worked , thanks for the help
