### ISSUE TITLE
Need a way to know when messages have been rejected by EH

### ISSUE THREAD

**Issue by nirmalpshah** [hdinsight/eventhubs-client#6]
Currently if messages are rejected by an Event Hub (in particular, due to throttling) there is no way to know the message failed to make it to EH.
A callback mechanism needs to be provided.  This abridged snippet shows how this can be done using the  Qpid library; it would be great to add a similar feature into this repo.

```java
org.apache.qpid.amqp_1_0.client.Sender.OutcomeAction action = (deliveryTag, outcome) -> {
  if (outcome instanceof Accepted) 
    // this is an accepted message
  else 
    // this is not accepted, example of response object in case of EH throttling
    // Rejected{error=Error{condition=com.microsoft:server-busy,description=The request was terminated because the entity is being throttled. Error code : 50002. Please wait 4 seconds and try again. TrackingId:..., Reference:030596ef-66f8-4927-ab8a-1deade4e41d1, Timestamp:11/10/2015 5:55:31 PM}}
};
org.apache.qpid.amqp_1_0.client.Sender sender = session.createSender("myeventhub");
org.apache.qpid.amqp_1_0.client.Message message = new Message(new Data(new Binary("hello!".getBytes())));
message.setDeliveryTag(new Binary("Some identifier").getBytes()));
sender.send(message, action);
```

**Comment by rtandonmsft** [comment]
@nirmalpshah I doubt any new features will be added to this client. All asks should now be tracked at: https://github.com/Azure/azure-event-hubs

This repository will only be in bug fixing mode until all clients move to the new proton-j based library.
