### ISSUE TITLE
Issue connecting to new German data center

### ISSUE THREAD

**Issue by dominicbetts** [hdinsight/eventhubs-client#8]
This library assumes the endpoint you are connecting to has the suffix .servicebus.windows.net. IoT Hub endpoints in the new German data center have a suffix .azure-devices.de making it impossible to connect using this library.

**Comment by rtandonmsft** [comment]
@dominicbetts The connection string builder in eventhubs-client does support taking different suffix:

Could you try that: https://github.com/hdinsight/eventhubs-client/blob/81762f9361c79eea82fdd7083eea73c8942676f9/src/main/java/com/microsoft/eventhubs/client/ConnectionStringBuilder.java

```java
 public ConnectionStringBuilder(String policyName, String policyKey,
      String namespace, String serviceFqdnSuffix) {
    connectionString = "amqps://" + policyName + ":" + encodeString(policyKey)
        + "@" + namespace + "." + serviceFqdnSuffix;
  }
```

Also - I would recommend looking at the official [azure-event-hubs](https://github.com/Azure/azure-event-hubs) for long term support directly by the event-hubs team.
